import { 
  LayoutDashboard,
  Building2, 
  ShieldAlert, 
  Users, 
  Shield, 
  FileText,
  Briefcase,
  MessageSquare,
  UserCircle,
  Orbit,
  ShieldCheck,
  Sparkles,
  GitFork,
  Folder,
  Compass,
  Target,
  Bookmark,
  Inbox,
  User,
  GraduationCap,
  Award,
  Trophy,
  CreditCard,
  Settings,
  TrendingUp,
  HandCoins,
  Globe,
  BarChart3
} from 'lucide-react';
import { type NavigationNode } from '../types/navigation.types';

export const navigationConfig: NavigationNode[] = [
  // 1. BUSINESS SECTION (Workspace-specific operations)
  {
    id: 'business-section',
    type: 'section',
    label: 'Business',
    translationKey: 'common:dashboard.sections.business',
    requiredRoles: ['BUSINESS', 'ADMIN'],
    children: [
      {
        id: 'workspace-dashboard',
        type: 'item',
        label: 'Dashboard',
        translationKey: 'common:dashboard.businessDashboard',
        href: '/workspace/[slug]/dashboard',
        icon: LayoutDashboard,
        exactMatch: true,
      },
      {
        id: 'workspace-listings',
        type: 'item',
        label: 'Listings',
        translationKey: 'common:dashboard.listings',
        href: '/workspace/[slug]/listings',
        icon: Globe,
      },
      {
        id: 'workspace-bookings',
        type: 'item',
        label: 'Bookings',
        translationKey: 'common:dashboard.bookings',
        href: '/workspace/[slug]/bookings',
        icon: TrendingUp,
      },
      {
        id: 'workspace-revenue',
        type: 'item',
        label: 'Revenue',
        translationKey: 'common:dashboard.revenue',
        href: '/workspace/[slug]/revenue',
        icon: HandCoins,
        requiredWorkspacePermissions: ['billing:invoice:view', 'billing:subscription:manage'],
      },
      {
        id: 'workspace-customers',
        type: 'item',
        label: 'Customers',
        translationKey: 'common:dashboard.customers',
        href: '/workspace/[slug]/customers',
        icon: Users,
      },
      {
        id: 'workspace-analytics',
        type: 'item',
        label: 'Analytics',
        translationKey: 'common:dashboard.analytics',
        href: '/workspace/[slug]/analytics',
        icon: BarChart3,
      },
    ],
  },

  // 2. PLATFORM SECTION (Global platform-level pages)
  {
    id: 'platform-section',
    type: 'section',
    label: 'Platform',
    translationKey: 'common:dashboard.sections.platform',
    children: [
      {
        id: 'job-board',
        type: 'item',
        label: 'Job Board',
        translationKey: 'common:dashboard.jobBoard',
        href: '/jobs',
        icon: Briefcase,
      },
      {
        id: 'forum',
        type: 'item',
        label: 'Forum',
        translationKey: 'common:dashboard.forum',
        href: '/forum',
        icon: MessageSquare,
      },
      {
        id: 'organizations',
        type: 'item',
        label: 'Organizations',
        translationKey: 'common:dashboard.organizations',
        href: '/workspace/organizations',
        icon: Building2,
      },
      {
        id: 'leaderboard',
        type: 'item',
        label: 'Leaderboard',
        translationKey: 'common:dashboard.ranking',
        href: '/ranking',
        icon: Trophy,
      },
    ],
  },

  // 3. MANAGEMENT SECTION (Workspace management and settings)
  {
    id: 'management-section',
    type: 'section',
    label: 'Management',
    translationKey: 'common:dashboard.sections.management',
    requiredRoles: ['BUSINESS', 'ADMIN'],
    children: [
      {
        id: 'workspace-members',
        type: 'item',
        label: 'Members',
        translationKey: 'common:dashboard.members',
        href: '/workspace/[slug]/members',
        icon: Users,
      },
      {
        id: 'workspace-roles',
        type: 'item',
        label: 'Roles',
        translationKey: 'common:dashboard.roles',
        href: '/workspace/[slug]/roles',
        icon: Shield,
        requiredWorkspacePermissions: ['organization:roles:view', 'organization:roles:manage'],
      },
      {
        id: 'workspace-billing',
        type: 'item',
        label: 'Billing',
        translationKey: 'common:dashboard.billing',
        href: '/workspace/[slug]/billing',
        icon: CreditCard,
        requiredWorkspacePermissions: ['billing:invoice:view', 'billing:subscription:manage'],
      },
      {
        id: 'workspace-settings',
        type: 'item',
        label: 'Settings',
        translationKey: 'common:dashboard.settings',
        href: '/workspace/[slug]/settings',
        icon: Settings,
        requiredWorkspacePermissions: ['organization:settings:edit', 'organization:profile:edit'],
      },
    ],
  },

  // 4. CANDIDATE SECTION (Personal developer dashboard - visible to USER/ADMIN roles)
  {
    id: 'candidate-section',
    type: 'section',
    label: 'Candidate',
    translationKey: 'common:dashboard.sections.candidate',
    requiredRoles: ['USER', 'ADMIN'],
    children: [
      {
        id: 'candidate-dashboard',
        type: 'item',
        label: 'Dashboard',
        translationKey: 'common:dashboard.candidateDashboard',
        href: '/user',
        icon: LayoutDashboard,
      },
      {
        id: 'candidate-profile',
        type: 'item',
        label: 'Professional Profile',
        translationKey: 'common:dashboard.profile',
        href: '/user/profile',
        icon: UserCircle,
      },
      {
        id: 'candidate-cv-group',
        type: 'group',
        label: 'My CV',
        translationKey: 'common:dashboard.cv',
        href: '/cv',
        icon: FileText,
        children: [
          {
            id: 'cv-overview',
            type: 'item',
            label: 'Overview',
            translationKey: 'common:cvManagement.overview',
            href: '/cv',
            icon: FileText,
            exactMatch: true,
          },
          {
            id: 'cv-basic-info',
            type: 'item',
            label: 'Basic Information',
            translationKey: 'common:cvManagement.sectionBasicInfo',
            href: '/cv?tab=basic-info',
            icon: User,
          },
          {
            id: 'cv-skills',
            type: 'item',
            label: 'Target Skills',
            translationKey: 'common:cvManagement.sectionSkills',
            href: '/cv?tab=skills',
            icon: Sparkles,
          },
          {
            id: 'cv-projects',
            type: 'item',
            label: 'Linked Projects',
            translationKey: 'common:cvManagement.sectionProjects',
            href: '/cv?tab=projects',
            icon: Folder,
          },
          {
            id: 'cv-experience',
            type: 'item',
            label: 'Work Experience',
            translationKey: 'common:cvManagement.sectionExperience',
            href: '/cv?tab=experience',
            icon: Briefcase,
          },
          {
            id: 'cv-education',
            type: 'item',
            label: 'Education',
            translationKey: 'common:cvManagement.sectionEducation',
            href: '/cv?tab=education',
            icon: GraduationCap,
          },
          {
            id: 'cv-achievements',
            type: 'item',
            label: 'Achievements & Certificates',
            translationKey: 'common:cvManagement.sectionAchievements',
            href: '/cv?tab=achievements',
            icon: Award,
          },
          {
            id: 'cv-preferences',
            type: 'item',
            label: 'Career Preferences',
            translationKey: 'common:cvManagement.sectionPreferences',
            href: '/cv?tab=preferences',
            icon: Target,
          },
        ],
      },
    ],
  },

  // 5. INTELLIGENCE SECTION (Talent analysis tools)
  {
    id: 'intelligence-section',
    type: 'section',
    label: 'Intelligence',
    translationKey: 'common:dashboard.sections.intelligence',
    requiredRoles: ['USER', 'ADMIN'],
    children: [
      {
        id: 'intelligence-capability-graph',
        type: 'item',
        label: 'Capability Graph',
        translationKey: 'common:dashboard.capabilityGraph',
        href: '/intelligence/capability-graph',
        icon: Orbit,
      },
      {
        id: 'intelligence-trust-score',
        type: 'item',
        label: 'Trust Score',
        translationKey: 'common:dashboard.trustScore',
        href: '/intelligence/trust-score',
        icon: ShieldCheck,
      },
      {
        id: 'intelligence-ai-analysis',
        type: 'item',
        label: 'AI Analysis',
        translationKey: 'common:dashboard.aiAnalysis',
        href: '/intelligence/ai-analysis',
        icon: Sparkles,
      },
      {
        id: 'intelligence-repositories',
        type: 'item',
        label: 'Repositories',
        translationKey: 'common:dashboard.repositories',
        href: '/settings/source-code-providers',
        icon: GitFork,
      },
    ],
  },

  // 6. SYSTEM ADMINISTRATION SECTION
  {
    id: 'admin-section',
    type: 'section',
    label: 'Administration',
    translationKey: 'common:dashboard.systemAdmin',
    requiredRoles: ['ADMIN'],
    children: [
      {
        id: 'admin-group',
        type: 'group',
        label: 'System Admin',
        translationKey: 'common:admin.systemAdmin',
        icon: ShieldAlert,
        children: [
          {
            id: 'admin-overview',
            type: 'item',
            label: 'Admin',
            translationKey: 'common:admin.dashboard',
            href: '/admin',
            exactMatch: true,
            icon: LayoutDashboard,
          },
          {
            id: 'admin-users',
            type: 'item',
            label: 'Users',
            translationKey: 'common:admin.users',
            href: '/admin/users',
            icon: Users,
            requiredPermissions: ['users:view:list'],
          },
          {
            id: 'admin-roles',
            type: 'item',
            label: 'Roles Matrix',
            translationKey: 'common:admin.rolesMatrix',
            href: '/admin/roles',
            icon: Shield,
            requiredPermissions: ['roles:view:list'],
          },
          {
            id: 'admin-audit-logs',
            type: 'item',
            label: 'Audit Trail',
            translationKey: 'common:admin.auditTrail',
            href: '/admin/audit-logs',
            icon: FileText,
            requiredPermissions: ['ai:audit:view'],
          },
        ],
      },
    ],
  },
];
