import { 
  LayoutDashboard,
  Building2, 
  ShieldAlert, 
  Users, 
  Shield, 
  FileText,
  Briefcase,
  MessageSquare,
  UserCircle,
  Orbit,
  ShieldCheck,
  Sparkles,
  Target,
  Inbox,
  GitFork,
  Folder
} from 'lucide-react';
import { type NavigationNode } from '../types/navigation.types';

export const navigationConfig: NavigationNode[] = [
  {
    id: 'general-section',
    type: 'section',
    label: 'General',
    translationKey: 'common:dashboard.sections.general',
    children: [
      {
        id: 'job-board',
        type: 'item',
        label: 'Job Board',
        translationKey: 'common:dashboard.jobBoard',
        href: '/jobs',
        icon: Briefcase,
      },
      {
        id: 'forum',
        type: 'item',
        label: 'Forum',
        translationKey: 'common:dashboard.forum',
        href: '/forum',
        icon: MessageSquare,
      },
    ],
  },
  {
    id: 'candidate-section',
    type: 'section',
    label: 'Candidate',
    translationKey: 'common:dashboard.sections.candidate',
    requiredRoles: ['USER', 'ADMIN'],
    children: [
      {
        id: 'candidate-dashboard',
        type: 'item',
        label: 'Dashboard',
        translationKey: 'common:dashboard.candidateDashboard',
        href: '/user',
        icon: LayoutDashboard,
      },
      {
        id: 'candidate-cv',
        type: 'item',
        label: 'My CV',
        translationKey: 'common:dashboard.cv',
        href: '/cv',
        icon: FileText,
      },
      {
        id: 'candidate-profile',
        type: 'item',
        label: 'Professional Profile',
        translationKey: 'common:dashboard.profile',
        href: '/user/profile',
        icon: UserCircle,
      },
    ],
  },
  {
    id: 'intelligence-section',
    type: 'section',
    label: 'Intelligence',
    translationKey: 'common:dashboard.sections.intelligence',
    requiredRoles: ['USER', 'ADMIN'],
    children: [
      {
        id: 'intelligence-capability-graph',
        type: 'item',
        label: 'Capability Graph',
        translationKey: 'common:dashboard.capabilityGraph',
        href: '/intelligence/capability-graph',
        icon: Orbit,
      },
      {
        id: 'intelligence-trust-score',
        type: 'item',
        label: 'Trust Score',
        translationKey: 'common:dashboard.trustScore',
        href: '/intelligence/trust-score',
        icon: ShieldCheck,
      },
      {
        id: 'intelligence-ai-analysis',
        type: 'item',
        label: 'AI Analysis',
        translationKey: 'common:dashboard.aiAnalysis',
        href: '/intelligence/ai-analysis',
        icon: Sparkles,
      },
    ],
  },
  {
    id: 'jobs-section',
    type: 'section',
    label: 'Jobs',
    translationKey: 'common:dashboard.sections.jobs',
    requiredRoles: ['USER', 'ADMIN'],
    children: [
      {
        id: 'jobs-recommended',
        type: 'item',
        label: 'Recommended Jobs',
        translationKey: 'common:dashboard.recommendedJobs',
        href: '/jobs?tab=recommended',
        icon: Target,
      },
      {
        id: 'jobs-applications',
        type: 'item',
        label: 'Applications',
        translationKey: 'common:dashboard.applications',
        href: '/jobs?tab=applied',
        icon: Inbox,
      },
    ],
  },
  {
    id: 'evidence-section',
    type: 'section',
    label: 'Evidence',
    translationKey: 'common:dashboard.sections.evidence',
    requiredRoles: ['USER', 'ADMIN'],
    children: [
      {
        id: 'evidence-repositories',
        type: 'item',
        label: 'Repositories',
        translationKey: 'common:dashboard.repositories',
        href: '/settings/source-code-providers',
        icon: GitFork,
      },
      {
        id: 'evidence-projects',
        type: 'item',
        label: 'Projects',
        translationKey: 'common:dashboard.projects',
        href: '/cv?tab=projects',
        icon: Folder,
      },
    ],
  },
  {
    id: 'business-section',
    type: 'section',
    label: 'Business',
    translationKey: 'common:dashboard.sections.business',
    requiredRoles: ['BUSINESS', 'ADMIN'],
    children: [
      {
        id: 'business-dashboard',
        type: 'item',
        label: 'Dashboard',
        translationKey: 'common:dashboard.businessDashboard',
        href: '/business',
        icon: Building2,
      },
    ],
  },
  {
    id: 'admin-section',
    type: 'section',
    label: 'Administration',
    translationKey: 'common:dashboard.systemAdmin',
    requiredRoles: ['ADMIN'],
    children: [
      {
        id: 'admin-group',
        type: 'group',
        label: 'System Admin',
        translationKey: 'common:admin.systemAdmin',
        icon: ShieldAlert,
        children: [
          {
            id: 'admin-overview',
            type: 'item',
            label: 'Admin',
            translationKey: 'common:admin.dashboard',
            href: '/admin',
            exactMatch: true,
            icon: LayoutDashboard,
          },
          {
            id: 'admin-users',
            type: 'item',
            label: 'Users',
            translationKey: 'common:admin.users',
            href: '/admin/users',
            icon: Users,
            requiredPermissions: ['users:view:list'],
          },
          {
            id: 'admin-roles',
            type: 'item',
            label: 'Roles Matrix',
            translationKey: 'common:admin.rolesMatrix',
            href: '/admin/roles',
            icon: Shield,
            requiredPermissions: ['roles:view:list'],
          },
          {
            id: 'admin-audit-logs',
            type: 'item',
            label: 'Audit Trail',
            translationKey: 'common:admin.auditTrail',
            href: '/admin/audit-logs',
            icon: FileText,
            requiredPermissions: ['ai:audit:view'],
          },
        ],
      },
    ],
  },
];
