-- Select and insert matching records into security_events
INSERT INTO security_events (
    "Id", "EventType", "Category", "Severity", "Status", "RiskScore", 
    "ConfidenceScore", "Description", "ActorUserId", "TargetUserId", 
    "OrganizationId", "IpAddress", "CorrelationId", "OccurrenceCount", 
    "CreatedAt", "UpdatedAt"
)
SELECT 
    "Id",
    "EventType",
    CASE 
        WHEN "EventType" LIKE 'USER_LOGIN%' OR "EventType" LIKE 'OTP%' OR "EventType" LIKE 'PASSWORD%' THEN 'Authentication'
        ELSE 'Session'
    END,
    CASE 
        WHEN "EventType" IN ('TOKEN_THEFT_DETECTED', 'SuspiciousActivity') THEN 'Critical'
        WHEN "EventType" LIKE '%FAILED%' THEN 'Low'
        ELSE 'Informational'
    END,
    'New',
    CASE 
        WHEN "EventType" = 'TOKEN_THEFT_DETECTED' THEN 90
        WHEN "EventType" LIKE '%FAILED%' THEN 15
        ELSE 0
    END,
    95,
    "Description",
    "ActorUserId",
    "TargetUserId",
    "OrganizationId",
    "IpAddress",
    '00000000-0000-0000-0000-000000000000'::uuid,
    1,
    "CreatedAt",
    "CreatedAt"
FROM "AuditLogs"
WHERE "EventType" IN (
    'USER_LOGIN_SUCCESS', 'USER_LOGIN_FAILED_CREDENTIALS', 'USER_LOGIN_FAILED_EMAIL', 
    'USER_LOGIN_FAILED_DISABLED', 'USER_LOGIN_FAILED_LOCKED', 'USER_LOGIN_UNVERIFIED', 
    'USER_GOOGLE_LOGIN_SUCCESS', 'USER_GOOGLE_LOGIN_BLOCKED', 'TAKEOVER_ATTEMPT_BLOCKED', 
    'ORGANIZATION_LOGIN_FAILED_CREDENTIALS', 'COMPANY_LOGIN_SUCCESS', 'TOKEN_THEFT_DETECTED', 
    'TOKEN_ROTATED', 'COMPANY_TOKEN_ROTATED', 'SESSION_REVOKED', 'ALL_OTHER_SESSIONS_REVOKED', 
    'SELF_REVOCATION_REJECTED', 'OTP_SENT', 'OTP_FAILED', 'OTP_VERIFIED', 'OTP_BYPASSED', 
    'SuspiciousActivity', 'PASSWORD_CREDENTIAL_CREATED', 'PASSWORD_CHANGED', 
    'PASSWORD_RECOVERY_COMPLETED', 'PASSWORD_SETUP_COMPLETED', 'PASSWORD_RECOVERY_FAILED', 
    'PASSWORD_SETUP_FAILED', 'PASSWORD_REUSE_BLOCKED', 'PASSWORD_SETUP_CONCURRENT_BLOCKED', 
    'CANDIDATE_PASSWORD_RECOVERY_REQUESTED', 'CANDIDATE_PASSWORD_RESET_SUCCESS',
    'ORG_PASSWORD_RECOVERY_OTP_DISPATCHED', 'ORG_PASSWORD_RESET_SUCCESS', 'CREDENTIAL_ROTATION'
);

-- Flag original audit logs as legacy security records
UPDATE "AuditLogs"
SET "IsLegacySecurityEvent" = TRUE
WHERE "EventType" IN (
    'USER_LOGIN_SUCCESS', 'USER_LOGIN_FAILED_CREDENTIALS', 'USER_LOGIN_FAILED_EMAIL', 
    'USER_LOGIN_FAILED_DISABLED', 'USER_LOGIN_FAILED_LOCKED', 'USER_LOGIN_UNVERIFIED', 
    'USER_GOOGLE_LOGIN_SUCCESS', 'USER_GOOGLE_LOGIN_BLOCKED', 'TAKEOVER_ATTEMPT_BLOCKED', 
    'ORGANIZATION_LOGIN_FAILED_CREDENTIALS', 'COMPANY_LOGIN_SUCCESS', 'TOKEN_THEFT_DETECTED', 
    'TOKEN_ROTATED', 'COMPANY_TOKEN_ROTATED', 'SESSION_REVOKED', 'ALL_OTHER_SESSIONS_REVOKED', 
    'SELF_REVOCATION_REJECTED', 'OTP_SENT', 'OTP_FAILED', 'OTP_VERIFIED', 'OTP_BYPASSED', 
    'SuspiciousActivity', 'PASSWORD_CREDENTIAL_CREATED', 'PASSWORD_CHANGED', 
    'PASSWORD_RECOVERY_COMPLETED', 'PASSWORD_SETUP_COMPLETED', 'PASSWORD_RECOVERY_FAILED', 
    'PASSWORD_SETUP_FAILED', 'PASSWORD_REUSE_BLOCKED', 'PASSWORD_SETUP_CONCURRENT_BLOCKED', 
    'CANDIDATE_PASSWORD_RECOVERY_REQUESTED', 'CANDIDATE_PASSWORD_RESET_SUCCESS',
    'ORG_PASSWORD_RECOVERY_OTP_DISPATCHED', 'ORG_PASSWORD_RESET_SUCCESS', 'CREDENTIAL_ROTATION'
);
